export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const SUBMIT_LUNCH_ORDER = "SUBMIT_LUNCH_ORDER";
export const SUBMIT_ADMIN_CREDENTIALS = "SUBMIT_ADMIN_CREDENTIALS";
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";
export default {
    SUBMIT_REGISTER, 
    SUBMIT_LUNCH_ORDER, 
    SUBMIT_ADMIN_CREDENTIALS, 
    ADMIN_LOGIN_REQUEST, 
    ADMIN_LOGIN_FAILURE, 
    ADMIN_LOGOUT,
    ADD_USER,
    ADD_USER_SUCCESS,
    ADD_USER_FAILURE
};